# Generated by Django 3.0.3 on 2020-05-25 19:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=50)),
                ('ad_price', models.FloatField()),
                ('img1', models.ImageField(max_length=255, upload_to='ad_img/')),
                ('img2', models.ImageField(max_length=255, upload_to='ad_img/')),
                ('img3', models.ImageField(max_length=255, upload_to='ad_img/')),
                ('img4', models.ImageField(max_length=255, upload_to='ad_img/')),
                ('ad_des', models.CharField(max_length=1000)),
                ('ad_post_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=15)),
                ('cat_icon', models.ImageField(max_length=255, upload_to='icon/')),
                ('cat_show', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=150)),
                ('msg_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('msg_regarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.cat'),
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.loc'),
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
