# Generated by Django 3.0.3 on 2020-06-09 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0002_auto_20200606_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first.ad'),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_regarding',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
