# Generated by Django 3.0.3 on 2020-07-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20200619_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_desc',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
