# Generated by Django 3.0.3 on 2020-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_userprofile_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loc',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
